version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env
    networks:
      - common_network
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file: 
      - .env
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}
    network_mode: "host"
    volumes:
      - .:/app
 
networks:
  common_network:
    driver: bridge